name: test
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py36_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.2.2=py36_0
  - python=3.6.9=h265db76_0
  - readline=7.0=h7b6447c_5
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - albumentations==0.4.6
    - h5py==2.10.0
    - ipyfilechooser==0.3.5
    - ipykernel==5.3.4
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab==2.2.6
    - jupyterlab-server==1.2.0
    - keras-preprocessing==1.1.2
    - matplotlib==3.3.1
    - medpy==0.4.0
    - notebook==6.1.3
    - numpy==1.18.0
    - opencv-python==4.4.0.42
    - pandas==1.1.1
    - pyyaml==5.3.1
    - scikit-image==0.17.2
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - seaborn==0.10.1
    - simpleitk==1.2.4
    - sklearn==0.0
    - tensorboard==2.3.0
    - tensorflow==2.3.0
prefix: /home/sven/anaconda3/envs/test

